spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trackerpro_dev
    username: root
    password: XJWyXnWnfXUdduKRpOdTfRlMBVIvkBYb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.trackerpro: DEBUG