server:
  port: 8080

spring:
  application:
    name: tracker-pro-spts
  
  profiles:
    active: development # Change to 'production' for MySQL
  
  # Static Resource Configuration
  web:
    resources:
      static-locations: classpath:/static/

---
# Development Profile (H2 Database)
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:trackerprodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

---
# Production Profile (MySQL Database)
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://localhost:3306/trackerprodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_mysql_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
      
# Logging Configuration
logging:
  level:
    com.trackerpro: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    
# Custom Application Properties
app:
  jwt:
    secret: trackerProSecretKey2024
    expiration: 86400000 # 24 hours in milliseconds
