server:
  port: ${PORT:8080}

spring:
  application:
    name: tracker-pro-spts
  profiles:
    active: production  # ✅ change to "development" if running locally

# =========================
# Development Profile (Local H2)
# =========================
---
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:h2:mem:trackerprodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

# =========================
# Production Profile (Railway MySQL)
# =========================
---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.trackerpro: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    root: WARN

app:
  jwt:
    secret: trackerProSecretKey2024
    expiration: 86400000
