server:
  port: 8080

spring:
  application:
    name: tracker-pro-spts
    
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:trackerprodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  # JPA Configuration  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # H2 Console Configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        
  # Static Resource Configuration
  web:
    resources:
      static-locations: classpath:/static/
      
# Logging Configuration
logging:
  level:
    com.trackerpro: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    
# Custom Application Properties
app:
  admin:
    email: admin@tracker.com
    password: admin123
  jwt:
    secret: trackerProSecretKey2024
    expiration: 86400000 # 24 hours in milliseconds