# MySQL Configuration Profile for Future Migration
spring:
  config:
    activate:
      on-profile: mysql
      
  datasource:
    url: jdbc:mysql://localhost:3306/trackerprodb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: false